// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfgsaenqxsupzbemhhds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmZ3NhZW5xeHN1cHpiZW1oaGRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc2MzYyNjksImV4cCI6MjA4MzIxMjI2OX0.4wdYLowL-sauIY0LtzUyeLPLt5LvaFtM9TtKqkN4kCo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});